apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q6h7redf3-go
  janus-idp.io/tekton: q6h7redf3-go
  backstage.io/kubernetes-id: q6h7redf3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q6h7redf3-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
